#!/usr/bin/env node
/**
 * 扫描 src/ 下所有 .ts / .tsx，收集形如 "prefix:name" 的 iconify 图标引用，
 * 从 @iconify/json 中按名提取单个 IconifyIcon，输出到 src/lib/icons.generated.ts。
 *
 * 运行时通过 @iconify/react/dist/offline 的 addIcon 注册到模块级 storage，
 * 让 <Icon icon="prefix:name" /> 完全离线渲染，绝不触发 setTimeout 死循环。
 *
 * 兜底清单：scripts/extra-icons.txt（每行一个 prefix:name，# 注释）
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getIconData } from "@iconify/utils";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const OUT = path.join(SRC, "lib", "icons.generated.ts");
const EXTRA = path.join(__dirname, "extra-icons.txt");
const ICON_JSON_DIR = path.join(ROOT, "node_modules", "@iconify", "json", "json");

// 匹配 icon="prefix:name" / icon='prefix:name'
const RE_JSX = /icon\s*=\s*["']([a-z][a-z0-9-]*):([a-z0-9-]+)["']/g;
// 匹配对象字面量 icon: "prefix:name"
const RE_OBJ = /\bicon\s*:\s*["']([a-z][a-z0-9-]*):([a-z0-9-]+)["']/g;

// 剔除 // 行注释、/* */ 块注释 以及 {/* */} JSX 注释
function stripComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
}

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, out);
    } else if (/\.(ts|tsx)$/.test(entry.name) && entry.name !== "icons.generated.ts") {
      out.push(full);
    }
  }
  return out;
}

function collectFromCode() {
  const found = new Map(); // prefix -> Set<name>
  for (const file of walk(SRC)) {
    const src = stripComments(fs.readFileSync(file, "utf8"));
    for (const re of [RE_JSX, RE_OBJ]) {
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(src))) {
        const [, prefix, name] = m;
        if (!found.has(prefix)) found.set(prefix, new Set());
        found.get(prefix).add(name);
      }
    }
  }
  return found;
}

function mergeExtras(found) {
  if (!fs.existsSync(EXTRA)) return;
  for (const raw of fs.readFileSync(EXTRA, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const m = /^([a-z][a-z0-9-]*):([a-z0-9-]+)$/.exec(line);
    if (!m) {
      console.warn(`[icons] extra-icons.txt: 无法解析 "${line}"，跳过`);
      continue;
    }
    const [, prefix, name] = m;
    if (!found.has(prefix)) found.set(prefix, new Set());
    found.get(prefix).add(name);
  }
}

function loadIconSet(prefix) {
  const file = path.join(ICON_JSON_DIR, `${prefix}.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function main() {
  const found = collectFromCode();
  mergeExtras(found);

  const lines = [
    "// AUTO-GENERATED by scripts/generate-icons.mjs — DO NOT EDIT",
    "// Run `pnpm icons` to regenerate.",
    "/* eslint-disable */",
    `import { addIcon } from "@iconify/react/dist/offline";`,
    "",
  ];

  let totalIcons = 0;
  const missing = [];
  const prefixes = [...found.keys()].sort();

  for (const prefix of prefixes) {
    const iconSet = loadIconSet(prefix);
    if (!iconSet) {
      const names = [...found.get(prefix)];
      missing.push(...names.map((n) => `${prefix}:${n}`));
      continue;
    }
    const names = [...found.get(prefix)].sort();
    lines.push(`// --- ${prefix} (${names.length}) ---`);
    for (const name of names) {
      const data = getIconData(iconSet, name);
      if (!data) {
        missing.push(`${prefix}:${name}`);
        continue;
      }
      // 移除 IconifyIcon 类型不识别的字段（hidden 是 ExtendedIconifyIcon 的弃用标记）
      const { hidden, ...cleanData } = data;
      lines.push(`addIcon(${JSON.stringify(`${prefix}:${name}`)}, ${JSON.stringify(cleanData)});`);
      totalIcons++;
    }
    lines.push("");
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
  console.log(`[icons] generated ${totalIcons} icons across ${prefixes.length} prefixes → ${path.relative(ROOT, OUT)}`);

  if (missing.length) {
    console.warn(`[icons] WARN ${missing.length} 图标在 @iconify/json 中找不到，将渲染为空 span（不影响构建）：`);
    for (const m of missing) console.warn(`  - ${m}`);
    console.warn(`[icons] 修正图标名或在 scripts/extra-icons.txt 补充别名后重新生成`);
  }
}

main();
